profile = "default"

[msbuild]
project = ["src/Core/Core.csproj", "src/TreasureSolver/TreasureSolver.csproj"]

[[pack]]
rid = ["win-x64", "win-arm", "win-arm64"]
kinds = ["zip"]

[nuget]
source = "github"

[github]
user = "Dofus-Batteries-Included"
repo = "DBI"
version_prefix = "v"