[msbuild]
project = ["src/Core/Core.csproj", "src/TreasureSolver/TreasureSolver.csproj"]

[nuget]
source = "https://nuget.pkg.github.com/Dofus-Batteries-Included/index.json"

[github]
user = "Dofus-Batteries-Included"
repo = "DBI"
version_prefix = "v"