name: Fetch game files

on:
  workflow_call:
    outputs:
      game_build_id:
        description: "Game build id"
        value: ${{ jobs.fetch-game-files.outputs.game_build_id }}
      game_version:
        description: "Game version"
        value: ${{ jobs.fetch-game-files.outputs.game_version }}

jobs:
  fetch-game-files:
    name: Fetch game files
    runs-on: windows-latest
    
    permissions:
      packages: read

    outputs:
      game_build_id: ${{ steps.read_game_build_id.outputs.DofusBuildId }}
      game_version: ${{ steps.download_latest_game_files.outputs.DofusVersion }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout
        uses: actions/setup-node@v4
        with:
          node-version: latest
        
      - name: Setup Github NPM registry for @dofus-batteries-included namespace
        run: |
          echo @dofus-batteries-included:registry=https://npm.pkg.github.com > ~/.npmrc
          echo //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }} >> ~/.npmrc

      - name: Install Cytrus v6
        run: npm i @dofus-batteries-included/cytrus-v6 -g

      - name: Download latest game files
        id: download_latest_game_files
        run: echo "DofusVersion=$(cytrus-v6 version -g dofus -b)" >> $GITHUB_OUTPUT

      - name: Download BepInEx
        run: curl https://builds.bepinex.dev/projects/bepinex_be/697/BepInEx-Unity.IL2CPP-win-x64-6.0.0-be.697%2B5362580.zip -o BepInEx.zip

      - name: Download latest game files
        run: cytrus-v6 download -g dofus -b -s "Dofus.exe,*.dll,Dofus_Data/*,Dofus_Data/il2cpp_data/**/*,Dofus_Data/Plugins/**/*,Dofus_Data/Resources/**/*" -o dofus-beta # Use beta for now

      - name: Extract BepInEx
        run: 7z x BepInEx.zip -odofus-beta -aoa

      - name: Run game once
        run: node scripts/bepinex-first-run dofus-beta\Dofus.exe
        timeout-minutes: 10

      - name: Read game build id
        id: read_game_build_id
        run: |
          $DofusBuildId=$(node scripts/read-build-guid.js dofus-beta/Dofus_Data/boot.config)
          echo "Found build id: $DofusBuildId"
          echo "DofusBuildId=$DofusBuildId" >> $GITHUB_OUTPUT

      - name: Upload Interop assemblies
        uses: actions/upload-artifact@v4
        with:
          name: interop-assemblies
          path: dofus-beta/BepInEx/interop/*