name: Poll game update

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  job:
    uses: Dofus-Batteries-Included/workflows/.github/workflows/create_release_on_game_updage.job.yml@main
    secrets:
      ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
    with:
      archive_name: release.zip
      metadata_path: DofusBatteriesIncluded/metadata.json

permissions:
  actions: write
  contents: write
  packages: read
