# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release

on:
  push:
    tags: "v*"
  workflow_dispatch:

jobs:
  fetch-game-files:
    uses: ./.github/workflows/fetch-game-files.job.yml
  
  build-release:
    name: Build & Release
    needs: fetch-game-files
    runs-on: windows-latest
    concurrency: release

    steps:
      - name: Display build information
        run: |
          echo "Build id: ${{ needs.fetch-game-files.outputs.game_build_id }}"
          echo "Version: ${{ needs.fetch-game-files.outputs.game_version }}"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Remove Interop assemblies
        run: rmdir src/Interop -r -force

      - name: Download Interop assemblies
        uses: actions/download-artifact@v4
        with:
          name: interop-assemblies
          path: src/Interop

      - name: Install .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Configure Github Nuget repository
        run: dotnet nuget add source --username ismailbennani --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Dofus-Batteries-Included/index.json"

      - name: Build, Tests, Cover, Pack and Publish
        shell: bash
        env:
          DofusBuildId: ${{ needs.fetch-game-files.outputs.game_build_id }}
          DofusVersion: ${{ needs.fetch-game-files.outputs.game_version }}
        run: |
          dotnet tool install --global dotnet-releaser
          dotnet-releaser run --nuget-token "${{secrets.GITHUB_TOKEN}}" --github-token "${{secrets.GITHUB_TOKEN}}" dotnet-releaser.toml

      - name: Package release
        run: |
          md dist/DofusBatteriesIncluded
          robocopy %CD%/src/*/bin/Release/net6.0/DofusBatteriesIncluded*.dll dist/DofusBatteriesIncluded
          cd dist
          7z a windows_x64.zip DofusBatteriesIncluded/

      - name: Upload compiled libraries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/windows_x64.zip
          asset_name: windows_x64.zip
          tag: ${{ github.ref }}

      - name: Write VERSION file that will be released
        run: echo "${{ needs.fetch-game-files.outputs.game_version }}" >> VERSION

      - name: Upload VERSION file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: VERSION
          asset_name: VERSION
          tag: ${{ github.ref }}

permissions:
  contents: write
  packages: write