# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release

on:
  release: 
    types: [published]
  workflow_dispatch:

jobs:
  fetch-game-files:
    uses: ./.github/workflows/fetch-game-files.job.yml
  
  build-release:
    name: Build & Release
    needs: fetch-game-files
    runs-on: windows-latest
    concurrency: release

    steps:
      - name: Display build information
        run: |
          echo "Build id: ${{ needs.fetch-game-files.outputs.game_build_id }}"
          echo "Version: ${{ needs.fetch-game-files.outputs.game_version }}"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Remove Interop assemblies
        run: rmdir src/Interop -r -force

      - name: Download Interop assemblies
        uses: actions/download-artifact@v4
        with:
          name: interop-assemblies
          path: src/Interop

      - name: Install .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Configure Github Nuget repository
        run: dotnet nuget add source --username ismailbennani --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Dofus-Batteries-Included/index.json"

      - name: Restore dependencies
        run: cd src/; dotnet restore

      - name: Build
        env:
          DofusBuildId: ${{ needs.fetch-game-files.outputs.game_build_id }}
          DofusVersion: ${{ needs.fetch-game-files.outputs.game_version }}
        run: cd src; dotnet pack --configuration Release --no-restore --output nuget/ -p:DofusBuildId=${{ needs.fetch-game-files.outputs.game_build_id }} -p:DofusVersion=${{ needs.fetch-game-files.outputs.game_version }}

      - name: Publish nugets
        run: |
          foreach($File in (Get-ChildItem "src/nuget/" -Recurse -Include *.nupkg)) {
              dotnet nuget push $File --source github --api-key ${{ secrets.GITHUB_TOKEN }}
          }

      - name: Package release
        if: ${{ github.event_name == 'release' }}
        run: |
          md dist/DofusBatteriesIncluded
          copy src/*/bin/Release/net6.0/DofusBatteriesIncluded*.dll dist/DofusBatteriesIncluded
          cd dist
          7z a release.zip DofusBatteriesIncluded/

      - name: Upload compiled libraries to release
        if: ${{ github.event_name == 'release' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/release.zip
          asset_name: release.zip
          tag: ${{ github.ref }}

      - name: Write VERSION file that will be released
        run: echo "${{ needs.fetch-game-files.outputs.game_version }}" >> VERSION

      - name: Upload VERSION file to release
        if: ${{ github.event_name == 'release' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: VERSION
          asset_name: VERSION
          tag: ${{ github.ref }}

permissions:
  contents: write
  packages: write