# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release

on:
  push:
    tags: "v*"
  workflow_dispatch:

jobs:
  call-fetch-game-files:
    uses: Dofus-Batteries-Included/DBI/.github/workflows/fetch-game-files.job.yml@main
  
  build-release:
    name: Build & Release
    needs: call-fetch-game-files
    runs-on: windows-latest
    concurrency: release

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Remove Interop assemblies
        run: rmdir src/Interop -r -force

      - name: Download Interop assemblies
        uses: actions/download-artifact@v4
        with:
          name: interop-assemblies
          path: src/Interop

      - name: Install .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Display build information
        run: |
          echo "Build id: ${{ needs.call-fetch-game-files.outputs.game_build_id }}"
          echo "Version: ${{ needs.call-fetch-game-files.outputs.game_version }}"

      - name: Build, Tests, Cover, Pack and Publish
        shell: bash
        env:
          DofusBuildId: ${{ needs.call-fetch-game-files.outputs.game_build_id }}
          DofusVersion: ${{ needs.call-fetch-game-files.outputs.game_version }}
        run: |
          dotnet tool install --global dotnet-releaser
          dotnet-releaser run --nuget-token "${{secrets.NUGET_TOKEN}}" --github-token "${{secrets.GITHUB_TOKEN}}" dotnet-releaser.toml

permissions:
  contents: write
  packages: read